name: Run Jupyter Notebooks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  prepare:
    runs-on: syne-tune_ubuntu-latest_16-core
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: check out Syne Tune
        uses: actions/checkout@v4
      - name: Set up Python 3.8
        uses: actions/setup-python@v5
      - name: Install dev dependencies
        run: python -m pip install -e '.[dev]'
      - name: Convert notebooks to python scripts
        id: set-matrix
        run: python ./.github/workflows/utils/notebooks2scripts.py
      - name: Upload converted python script
        uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4.3.1
        with:
          name: converted_notebooks
          path: examples/notebooks/

  tests:
    needs: prepare
    strategy:
      fail-fast: false
      matrix:
        script: ${{ fromJSON(needs.prepare.outputs.matrix)}}
    uses: ./.github/workflows/run-syne-tune.yml
    with: 
      download-artifact-name: converted_notebooks
      download-artifact-path: examples/notebooks/
      script-path: examples/notebooks/${{ matrix.script }}
      extras-require: basic
      additional-command: pip install xgboost
